############# English navigation ##############

# main menu
[[main]]
weight = 1
url = "homepage/grid/"
name = "Maison"
hasChildren = false

[[main]]
weight = 2
url = "about/"
name = "Sur"

[[main]]
weight = 3
url = "author/"
name = "Auteurs"
hasChildren = true

[[main]]
weight = 4
url = "blog/"
name = "Blogues"
hasChildren = true

[[main]]
weight = 5
url = "tags/"
name = "Marquer"

[[main]]
weight = 6
url = "categories/"
name = "Catégories"

[[main]]
weight = 7
url = "contact/"
name = "Contact"


############################# Footer Menu ########################
[[footer]]
weight = 1
url = "about/"
name = "Sur"

[[footer]]
weight = 2
url = "authors/"
name = "Auteurs"

[[footer]]
weight = 3
url = "privacy/"
name = "Confidentialité"

[[footer]]
weight = 4
url = "terms-conditions/"
name = "Termes et Conditions"