############# English navigation ##############

# main menu
[[main]]
weight = 1
url = "homepage/grid/"
name = "Home"
hasChildren = false

[[main]]
weight = 2
url = "about/"
name = "About"
  
[[main]]
weight = 3
url = "author/"
name = "Authors"
hasChildren = true

  [[main]]
  parent = "Authors"
  weight = 1
  url = "author/"
  name = "All"

  [[main]]
  parent = "Authors"
  weight = 2
  url = "author/jonny"
  name = "Jonny Catlett"

  [[main]]
  parent = "Authors"
  weight = 3
  url = "author/reid"
  name = "Reid Spencer"

[[main]]
weight = 4
url = "#"
name = "Blogs"
hasChildren = true

  [[main]]
  parent = "Blogs"
  weight = 2
  url = "reid/"
  name = "Reid Spencer"

  [[main]]
  parent = "Blogs"
  weight = 1
  url = "jonny/"
  name = "Jonny Catlett"

[[main]]
weight = 5
url = "#"
name = "Tags"
hasChildren = true

  [[main]]
  parent = "Tags"
  weight = 2
  url = "tags/"
  name = "All Tags"
  
  [[main]]
  parent = "Tags"
  weight = 3
  url = "tags/photography/"
  name = "Photography"

[[main]]
weight = 6
url = "$"
name = "Categories"
hasChildren = true

  [[main]]
  parent = "Categories"
  weight = 1
  url = "categories/"
  name = "All"

  [[main]]
  parent = "Categories"
  weight = 2
  url = "categories/photography/"
  name = "Photography"

[[main]]
weight = 7
url = "contact/"
name = "Contact"


############################# Footer Menu ########################
[[footer]]
weight = 1
url = "about/"
name = "About"

[[footer]]
weight = 2
url = "authors/"
name = "Authors"

[[footer]]
weight = 3
url = "privacy/"
name = "Privacy"

[[footer]]
weight = 4
url = "terms-conditions/"
name = "Terms & Conditions"