############# English navigation ##############

# main menu
[[main]]
weight = 1
url = "homepage/grid/"
name = "Home"
hasChildren = false

[[main]]
weight = 2
url = "about/"
name = "About"
  
[[main]]
weight = 3
url = "author/"
name = "Authors"

[[main]]
weight = 4
url = "blog/"
name = "Blogs"

[[main]]
weight = 5
url = "tags/"
name = "Tags"

[[main]]
weight = 6
url = "categories/"
name = "Categories"

[[main]]
weight = 7
url = "contact/"
name = "Contact"


############################# Footer Menu ########################
[[footer]]
weight = 1
url = "about/"
name = "About"

[[footer]]
weight = 2
url = "author/"
name = "Authors"

[[footer]]
weight = 3
url = "privacy/"
name = "Privacy"

[[footer]]
weight = 4
url = "terms-conditions/"
name = "Terms & Conditions"