matrix:
  - name: Markdown
    aspell:
      lang: en
    dictionary:
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - 'content/english/*.md'
      - 'content/english/**/*.md'
      - 'content/english/**/*.html'
      - README.md
    default_encoding: utf-8
