# This file is for render site varibles and plugins
# don't remove this file.
# The presence of this file is for compatibility with Blogdown and Forestry.
#
# The actual configuration files are stored in the `config/_default/` folder.


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
improving_blue = "#005596"
improving_light_blue = "#4597D3"
improving_green_accent = "#5BC2A7"
improving_orange_accent = "#F5BB41"
improving_gray_accent = "#A7A8A9"
improving_purple_accent = "#9D1D96"
body_color = "#fff"
border_color = "#ACB9C4"
dark_body_color = "#1E262C"
dark_text_color = "#cbcbcb"
dark_text_light = "#959595"
dark_text_dark = "#F5BB41"
dark_border_color = "#5BC2A7"
black = "#000"
white = "#fff"
dark = "#9D1D96"
light = "#F5BB41"
gray = "#A7A8A9"
dark_gray = "#222"

# font variables
# base font size for full website,
font_size = "16px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.25" # default is "majorThird": 1.25

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Work+Sans:wght@400;500;600"
font_primary = "Nunito:wght@400;500;600;700"
font_primary_type = "sans-serif" # [serif/sans-serif]
font_secondary = "Poppins:wght@400;500;600;800"
font_secondary_type = "sans-serif" # [serif/sans-serif]
font_icon = "Font Awesome 6 Free" # https://fontawesome.com/v6.0/icons/


############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.bundle.js"
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/instagram-feed/instagram-feed.js"
[[params.plugins.js]]
link = "https://cpwebassets.codepen.io/assets/embed/ei.js"
attributes = "async"
